### ISSUE TITLE
Add unit test

### ISSUE THREAD

**Issue by renanbr** [zendframework/ZendSkeletonApplication#179]
Add unit test for Application module as described in http://framework.zend.com/manual/2.1/en/tutorials/unittesting.html

In addition, when an application has two or more modules, it would be nice provide a way to run all tests in all modules and generate a unified phpunit log files (such junit and coverage).

**Comment by gianarb** [comment]
Feedback about this issue? :+1:

**Comment by akrabat** [comment]
Unit testing isn't part of this skeleton.
