### ISSUE TITLE
submodule & composer dependency confusion

### ISSUE THREAD

**Issue by dennis-fedco** [zendframework/ZendSkeletonApplication#226]
I am new to ZF2.  I have decided to download ZendSkeletonApplication to ease start of development.  I will be developing my own modules for my application.  I will also be using various vendor modules.

So I did `git clone git://github.com/zendframework/ZendSkeletonApplication.git`

Then I did `php composer.phar update`

Then I've heard of submodules so I did `git submodule init` and `git submodule update`

Now I am confused.  I have two folders `vendor/ZF2`, and `zendframework`, both containing ZF2 library but of wildly different versions.  

I am not sure if I should be using composer or submodules going forward.  I am new to both and both are present in the most basic ZendSkeletonApplication.  Am I supposed to use them both?  Is one better than another?  Is one of those to be deprecated?  Is one easier to maintain then another?  

I am surprised composer and submodules are not interoperable, i.e. not using the same folder.  Maybe it is on purpose.  ZF2 git submodule points to dev version that is 6 month old, so perhaps it is no longer the recommended way of doing things, and maybe is a hint to use composer.  So I should be using composer, yes?

If I missed something, please explain.  Thanks.

**Comment by Maks3w** [comment]
Now the project rely fully in composer and does not have submodules
