### ISSUE TITLE
Placeholder should be commented out

### ISSUE THREAD

**Issue by joshribakoff** [zendframework/ZendSkeletonApplication#228]
See here: https://github.com/zendframework/ZendSkeletonApplication/blob/master/module/Application/config/module.config.php#L95-L101

The empty array value should be commented out. Since it is not, it has the consequence that if someone defines that key earlier, the empty one overrides it, causing theirs to not take affect - or they have two "console" parameters with only one of them taking affect. I feel strongly that it should be commented out since its providing nothing but an empty array. If someone wants to use it, they uncomment it.

**Comment by Martin-P** [comment]
> Since it is not, it has the consequence that if someone defines that key earlier, the empty one overrides it, causing theirs to not take affect - or they have two "console" parameters with only one of them taking affect.

Config files get merged, not replaced. If a key already exists, the key and value will be preserved. This empty array does not overwrite anything, even if the key already exists.

**Comment by Martin-P** [comment]
Ping @Ocramius: I think this can be closed as not an issue?

**Comment by akrabat** [comment]
I've tested this with zf-development-mode and, as @Martin-P  says, the placeholder does not affect other console route configuration.
