### ISSUE TITLE
.htaccess listing existing directories

### ISSUE THREAD

**Issue by rafaame** [zendframework/ZendSkeletonApplication#229]
The problem: the .htaccess is allowing Apache to list the contents of existing directories inside the directory public

How to reproduce the problem: create a directory called "admin" inside "public" directory. Try to access the application using the URL: example.com/admin. The contents of directory "admin" will now be listed in the screen.

How to fix: I changed the .htaccess code to the following http://d.pr/n/pgMs and it worked

**Comment by akrabat** [comment]
I agree with @Ocramius. This is a server set up issue.
