### ISSUE TITLE
problems with autoload from netbeans

### ISSUE THREAD

**Issue by AlexandrKozyr** [zendframework/ZendSkeletonApplication#274]
When try to create a project with ZendSkeletonApplication get a problem from Composer: 

"C:\ProgramData\ComposerSetup\bin\composer.bat" "--ansi" "--no-interaction" "install"
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - zendframework/zendframework 2.3.x-dev requires php >=5.3.23 -> no matching package found.
    - zendframework/zendframework 2.3.3 requires php >=5.3.23 -> no matching package found.
    - zendframework/zendframework 2.3.2 requires php >=5.3.23 -> no matching package found.
    - zendframework/zendframework 2.3.1 requires php >=5.3.23 -> no matching package found.
    - zendframework/zendframework 2.3.0 requires php >=5.3.23 -> no matching package found.
    - Installation request for zendframework/zendframework 2.3.* -> satisfiable by zendframework/zendframework[2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
Готово.

Can someone help me?

**Comment by Ocramius** [comment]
You have an old version of PHP installed: the minimum requirement for ZF 2.3.* is PHP 5.3.23

**Comment by AlexandrKozyr** [comment]
no, i checked it in console.

**Comment by Ocramius** [comment]
`php >=5.3.23 -> no matching package found` means that PHP with that version couldn't be found. Run `php --version`

**Comment by AlexandrKozyr** [comment]
Oh y 5.3.13 i have. Thank you.))
