### ISSUE TITLE
zf2 package for skeleton-application

### ISSUE THREAD

**Issue by DonCarlosGraz** [zendframework/ZendSkeletonApplication#294]
hi!

I noticed that there is no 2.4.x package for the skeleton-application (https://github.com/zendframework/ZendSkeletonApplication) on
https://packages.zendframework.com/

Is this planned in the near future?

Thanks in advance

**Comment by gianarb** [comment]
Hi! In this moment 2.4.x tag doesn't exists

**Comment by DonCarlosGraz** [comment]
I guess the commit https://github.com/zendframework/ZendSkeletonApplication/commit/e2e1c69fc80ed55b21762f70d19e87df34248b06 should be tagged. 

Thanks in advance

**Comment by gianarb** [comment]
Why?
Sorry but do you download skeleton app from composer?

Thanks

**Comment by DonCarlosGraz** [comment]
Yes, I use it with composer.

When I run the following command (reference [1]) I can only download the version 2.5:
php composer.phar create-project --stability="dev" zendframework/skeleton-application path/to/install

Following command will fail:
php composer.phar create-project -sdev --repository-url="https://packages.zendframework.com" zendframework/skeleton-application:2.4.2 path/to/install

Since 2.4 is the LTS version [2] I think to provide a package would be a good idea.

Just for clarification: I have no problem to clone the git repository, but maybe this could help other developers :)

[1] http://framework.zend.com/manual/current/en/user-guide/skeleton-application.html
[2] http://framework.zend.com/long-term-support/

**Comment by davoudrafati** [comment]
looks like there is no tag with 2.4.x version
this is a big problem

**Comment by samsonasik** [comment]
Why you need 2.4 version for skeleton? you could just update composer.json and update with specific zf version, no?

**Comment by rbroen** [comment]
The problem is that there is a 2.0 version of the documentation with the wrong structure and that is misleading. Google seems to love this page. I feel this page should be altered or removed.

**Comment by DonCarlosGraz** [comment]
Hm.
I personally need no 2.4 version for skeleton and yes I could update composer.json an no this is not a  big problem...
I just wonder why no skeleton application for a LTS release is offered.

Should I close this issue?

**Comment by akrabat** [comment]
In my opinion 2.4 LTS is for existing ZF2 users. New users should start on 2.5 with a view to migrating to 3.0 when available.

If a particular user wants to stay on 2.4, then they should know enough to update their composer.json appropriately. I'm not against putting some tags in place though.

**Comment by gianarb** [comment]
I have the same opinion of @akrabat.. We should pull the community to use the last version of framework..

if a single company decide to use an old but LTS version is its choice.. :+1:

**Comment by samsonasik** [comment]
installing ZendSkeletonApplication should be for new project. While the new project has php 5.3/5.4 requirement, we can use git clone, and change the version. OR, the other choice is to update current php requirement in composer.json to 5.3.23, so, when user has 5.5+, it can install zf 2.5, otherwise, should will automatically install zf 2.3

**Comment by samsonasik** [comment]
sorry, 2.4
