### ISSUE TITLE
Need a coma at line 65

### ISSUE THREAD

**Issue by iamkdev** [zendframework/ZendSkeletonApplication#295]
Need a coma(,) at the end of the line 65

**Comment by gianarb** [comment]
HI! :) Can you help me to understand? File?

Thanks

**Comment by iamkdev** [comment]
Oh Yes. My bad. File  config/application.config.php
No so serious but I noticed.

**Comment by gianarb** [comment]
Would you submit a PR?
Thanks

**Comment by samsonasik** [comment]
I created pr #297 for it

**Comment by samsonasik** [comment]
#297 merged, it can be closed now
