### ISSUE TITLE
Recommended Project Directory Structure

### ISSUE THREAD

**Issue by rbroen** [zendframework/ZendSkeletonApplication#296]
I really appreciate the Skeleton application.

Would it be a good idea to follow the recommended project directory structure?
http://framework.zend.com/manual/2.0/en/ref/project.structure.html

(of is the structure on that page the ZF1 structure?)

**Comment by jeremiahsmall** [comment]
That is ZF1 structure. Docs need updating, not skeleton app.

**Comment by fadoe** [comment]
rboen linked the docs for version 2.0. In other versions this page don't exists anymore.

**Comment by rbroen** [comment]
Tnx for clearing it up guys!
