### ISSUE TITLE
composer.lock is included while it should be ignored by git

### ISSUE THREAD

**Issue by xtreamwayz** [zendframework/ZendSkeletonApplication#301]
As the title says. composer.lock is included while it should be excluded by .gitignore.

**Comment by gianarb** [comment]
Thanks

**Comment by jeremiahsmall** [comment]
The decision was made that skeleton apps should include the .lock file. You'll have to search through the threads, but it's been recently added to both this one and the Apigility one after some discussion.

**Comment by gianarb** [comment]
@jeremiahsmall the problem is different. Composer.lock is included but the are a little bug into gitignore

**Comment by jeremiahsmall** [comment]
The PR that adds composer.lock is here for refererence https://github.com/zendframework/ZendSkeletonApplication/pull/286
