### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by ThaDafinser** [zendframework/ZendSkeletonApplication#303]
Hello,

when using the command on http://framework.zend.com/manual/current/en/user-guide/skeleton-application.html

The skeleton still install ZF 2.3.3

**Comment by samsonasik** [comment]
ping @weierophinney

**Comment by jeremiahsmall** [comment]
I think the problem is that packagist is still caching versions (tired to commits), because the project doesn't have tags any more. https://packagist.org/packages/zendframework/skeleton-application

**Comment by vrkansagara** [comment]
@ThaDafinser 

Can you try following command first.
```php
php composer.phar clear-cache
```

Can you give a try to manual edit the composer file with latest one. and check weather your problem is solved or not.

**Comment by ThaDafinser** [comment]
Wont try the `clear-cache` command.
Even if it's a skeleton application, it still needs a (stable) release IMO.
