### ISSUE TITLE
Zf2 error

### ISSUE THREAD

**Issue by andresetevejob** [zendframework/ZendSkeletonApplication#310]
Hi All, 
I use zf2.5 on windows and i have this error when i start my project : 
Fatal error: Uncaught exception 'RuntimeException' with message 'Unable to load ZF2. Run `php composer.phar install` or define a ZF2_PATH environment variable

**Comment by websafe** [comment]
And have you done `php composer.phar install`?

**Comment by vrkansagara** [comment]
Can you follow an instruction given on README file her https://github.com/zendframework/ZendSkeletonApplication/blob/master/README.md

Here is clear instruction how to quick start with the project.
