### ISSUE TITLE
Blog application returns a blank screen for add action

### ISSUE THREAD

**Issue by Farsideman** [zendframework/ZendSkeletonApplication#311]
Followed the Blog tutorial to the letter. Double checked all code. Ran application. List of Blogs displayed. Ran the new post action. Form displayed. Inserted new post. Blank screen displayed and route remained as /blog/add and not the expected /blog. No errors reported to screen or recorded in server logs. Manually returned to /blog and list of blogs displayed including the inserted new post. Same type of result with the Album tutorial as reported in #308.

Using MAMP

**Comment by vrkansagara** [comment]
Hey, @Farsideman  
Have you checked your  `.htaccess` file with https://github.com/zendframework/ZendSkeletonApplication/blob/master/public/.htaccess

And make sure you have `mod_rewrite` would be enable while you are checking.

**Comment by Farsideman** [comment]
Yes, it is enabled. Code worked up until the next update. 

John

**Comment by weierophinney** [comment]
Please report issues discovered when working with the tutorials to the documentation repository, not the skeleton. Currently, this is https://github.com/zendframework/zf2-documentation, but, very shortly, this will be https://github.com/zendframework/tutorials (I'm actually right now working on updating the blog tutorial for zend-mvc v3, and should have it published in the next few days).
