### ISSUE TITLE
Parse error module.config.php on line 78

### ISSUE THREAD

**Issue by Jokersoft** [zendframework/ZendSkeletonApplication#312]
After last commit 2c9e759f873b7763c4437c019d45b780dbc6fefb I got 
Parse error: syntax error, unexpected T_CLASS, expecting T_STRING or T_VARIABLE or '$' in ...module/Application/config/module.config.php on line 78
on php 5.3.29

**Comment by Ocramius** [comment]
@Jokersoft upgrade to PHP 5.5 as per https://github.com/zendframework/ZendSkeletonApplication/blob/6ba430f6a2006d9f37c24b039fda3488e8681c91/composer.json#L11
