### ISSUE TITLE
Kill non-composer installation methods?

### ISSUE THREAD

**Issue by Ocramius** [zendframework/ZendSkeletonApplication#313]
About time, no?

**Comment by RalfEggert** [comment]
Yep! Makes everything easier for beginners.

**Comment by gianarb** [comment]
:+1:

**Comment by Stanimirdim92** [comment]
:+1:

**Comment by gianarb** [comment]
How can we proceed? I'm ready to delete all lines :)

**Comment by Stanimirdim92** [comment]
Any chance to remove init_autoloader and move $loader in index.php? @Ocramius

**Comment by Ocramius** [comment]
That's the idea.

**Comment by Stanimirdim92** [comment]
Do it, pretty please.

**Comment by Moln** [comment]
:+1:

**Comment by Thinkscape** [comment]
Yup
On Tue, May 17, 2016 at 7:20 AM, Moln <notifications@github.com> wrote:

> [image: :+1:]
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/zendframework/ZendSkeletonApplication/issues/313#issuecomment-219621885>
>
-- 
Artur Bodera
abodera@gmail.com
http://thinkscape.pro

**Comment by weierophinney** [comment]
Accomplished with #329 (still to be released).
