### ISSUE TITLE
Problems bringing vagrant up

### ISSUE THREAD

**Issue by func0der** [zendframework/ZendSkeletonApplication#321]
I try to start the vagrant box, but it gives me an error about not finding the box.

```
# vagrant up --provider virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The box 'bento/ubuntu-14.04' could not be found.
```

I saw that this part has been recently changed. Maybe for the worse?

**Comment by Maks3w** [comment]
Are you using an up to date version of Vagrant? At least >= 1.6

**Comment by func0der** [comment]
I did not see a requirement for that. Where does the README say something about that?

I had indeed an older version, because Ubuntu had an older version in their repositories. I installed it from the vagrant site and it worked.
Anyway, I would say that having a minimum vagrant version is a requirement that should be noted somewhere.

**Comment by Maks3w** [comment]
/fw @akrabat 

Reference https://github.com/zendframework/ZendSkeletonApplication/pull/288#discussion_r32207893
