### ISSUE TITLE
skel app does not work...

### ISSUE THREAD

**Issue by flobee** [zendframework/ZendSkeletonApplication#324]
when trying to add a module e.g. to work with the documentation to implement a sample blog: http://framework.zend.com/manual/current/en/in-depth-guide/first-module.html
It seem that vendors/framework version 2.4.9 (as zip download) up to version 2.5.3 (current) will not work because of many changes. only the composer files in here let zend nearly get work but not when adding more modules. :-( Its really hard to get into it even when comming from zf1.

**Comment by vrkansagara** [comment]
Hello @flobee 

Appreciate that you give a try to use zf2 but I have worked a lot many time with this url
 >http://framework.zend.com/manual/current/en/in-depth-guide/first-module.html

Am really sure that the documentation provided by the community are enough and true and fair till date.

>It seem that vendors/framework version 2.4.9 (as zip download) up to version 2.5.3 (current) will not work 

While you are using the composer than no need to download a manual package of zend framework.

just try  `composer create-project -n -sdev zendframework/skeleton-application path/to/install` 
Which is clearly mentioned on the README file. here 
https://github.com/zendframework/ZendSkeletonApplication

If anything I can help you thank Please.

**Comment by flobee** [comment]
thx, that links make me break and commiting my solution at #325 it tooks me too many hours already, leave me alone... today :-D

**Comment by vrkansagara** [comment]
I have already give so many hours to make things up and running , now am helping out those. :-D

**Comment by flobee** [comment]
:-D too hard geeting into details, i've wrote a blog post for those which may need help, google is to full to get good answers. happy zf2 :-)
