### ISSUE TITLE
PHP >= 5.5 must be added as note to readme.md

### ISSUE THREAD

**Issue by flobee** [zendframework/ZendSkeletonApplication#326]
Hi
Like mentiond in zf2 repo, its missing in here a must have information. 
--->---
SYSTEM REQUIREMENTS

Zend Framework 2 requires **PHP 5.5** or later; we recommend using the latest PHP version whenever possible.
---<---

**Comment by weierophinney** [comment]
@flobee That requirement is true only starting with ZF 2.5 and up; below that, we still supported PHP 5.3. As such, it depends on the version of the skeleton you're requesting, and, currently, the latest stable is using zendframework/zendframework at `~2.0`.
