### ISSUE TITLE
unable to fetch or create an instance for Zend\Db\Adapter\Adapter

### ISSUE THREAD

**Issue by akashwebdev** [zendframework/ZendSkeletonApplication#328]
Using ZF2.4, php 5.5+, XAMPP

Am getting this issue when am trying to follow Zend Album model setup. I tired moving my config _from global to config.module.php_ (as suggested in some tutorials) but no luck. 

Also I tried updating the application.config.php to update **config_glob_paths** and prepend ../../../ to the global,local autoloads, but again sadly no luck. Am strickly following http://framework.zend.com/manual/current/en/user-guide/skeleton-application.html documentation.

Any help would be greatly appreciated. 
Thanks in anticipation. 

Regards

**Comment by akashwebdev** [comment]
Working fine after downloading the ZF2 from github and following the tutorial as posted in the documentation. **Worked Like a charm**.

Regards,

**Comment by Ocramius** [comment]
Hey @akashwebdev, just a heads up: the information you initially provided was insufficient to help you out.

Next time, please state:

 * what you tried
 * what the expected result was
 * what result you got instead (error messages, etc)

Cheers

**Comment by akashwebdev** [comment]
Hi Ocramius,

Sure will keep that in mind next time. 

Regards,
