### ISSUE TITLE
PHP Version Mismatch

### ISSUE THREAD

**Issue by seth-reeser** [zendframework/ZendSkeletonApplication#331]
The README says:

> The simplest way to get started if you are using PHP 5.4 or above is to start the internal PHP cli-server in the root directory:

However composer.json is at:
````
    "require": {
        "php": ">=5.5",
        "zendframework/zendframework": "~2.5"
    }

**Comment by jeremiahsmall** [comment]
Seems okay to me. The point is that the php cli-server was introduced in 5.4

**Comment by seth-reeser** [comment]
OK - I see the specificity now, I suppose the problem I faced was determining the minimum PHP version. I would suggest highlighting it as Zend Framework 2.5.0 introduced the PHP 5.5 minimum and CentOS/RHEL 7 are still on PHP 5.4 from the main trunk... Long story short, I was adding Zend Framework 2.0.* <=2.4.* support to our website and workflow management platform, [Catapult](https://github.com/devopsgroup-io/catapult#supported-software) and ran into the confusion.

**Comment by weierophinney** [comment]
I've been updating and removing such verbiage as I prepare the new tutorials at https://github.com/zendframework/tutorials

Thanks, @seth-reeser !

**Comment by seth-reeser** [comment]
@weierophinney, fantastic - thank you!
