### ISSUE TITLE
Update the CSS and JS assets

### ISSUE THREAD

**Issue by RalfEggert** [zendframework/ZendSkeletonApplication#333]
The assets for CSS and JS are a little outdated. Should be updated to newer versions, shouldn't they?

**Comment by froschdesign** [comment]
Also "jQuery", "Respond.js" and "HTML5 Shiv" should be removed.

**Comment by weierophinney** [comment]
@RalfEggert Any chance you'd be willing to provide the updated versions? :grin:

**Comment by weierophinney** [comment]
Looks like #309 will do this for us!
