### ISSUE TITLE
Update error views

### ISSUE THREAD

**Issue by webimpress** [zendframework/ZendSkeletonApplication#342]
Guys,
what do you think about updating error views (`404.phtml` and `index.phtml`)?
I don't like this old style...

For example closing tag is not in the same column what opening tag:
https://github.com/zendframework/ZendSkeletonApplication/blob/develop/module/Application/view/error/404.phtml#L35-L44

missing some indents for if/while bodies:
https://github.com/zendframework/ZendSkeletonApplication/blob/develop/module/Application/view/error/index.phtml#L27-L60

and generally the whole style of these files isn't so nice.

What do you think? Do you prefer to use `if (...): ... endif;` or better with braces `{ ... }` ?

**Comment by alextech** [comment]
bad indentation for templates is pretty annoying, especially if it produces badly indented output to browser. Fixing that would be nice.
using `if (..): ... endif;` is a commonly accepted convention for HTML mix since its easier to trace in IDE than bracket matching.

**Comment by weierophinney** [comment]
Fixed recently with #344.
