### ISSUE TITLE
Describe difference in PSR-7 middleware dispatcher

### ISSUE THREAD

**Issue by xorock** [zendframework/ZendSkeletonApplication#350]
https://docs.zendframework.com/tutorials/getting-started/skeleton-application/
Docs contains only a screenshot of available options. One of them is "Would You like to use PSR-7 middleware dispatcher?"
Could You describe what it will change when selecting yes/no and how application should be written in these two scenarios?

**Comment by samsonasik** [comment]
I wrote tutorial about that: https://samsonasik.wordpress.com/2016/03/01/start-using-middleware-approach-with-new-zend-mvc/ , for middleware in event listener, you can read this: https://zendframework.github.io/zend-mvc/cookbook/middleware-in-listeners/

**Comment by weierophinney** [comment]
@xorock The only difference that occurs is that if selected, we add `zendframework/zend-psr7bridge` as an application dependency; once added, you can then use the included `MiddlewareDispatcher`, which we document in the zend-mvc documentation, and for which @samsonasik has written an additional tutorial.
