### ISSUE TITLE
ZendDeveloperTools

### ISSUE THREAD

**Issue by snapshotpl** [zendframework/ZendSkeletonApplication#351]
Skeleton contains default config for ZendDeveloperTools, however package isn't required in composer. It will increase developers start with framework, isn't it?

**Comment by snapshotpl** [comment]
Ok, I see now that's it's definend in `extra`. However during install I don't get any question

**Comment by samsonasik** [comment]
you should get it now:
```
    Do you want a minimal install (no optional packages)? Y/n
n

    Would you like to install the developer toolbar? y/N
y
    Will install zendframework/zend-developer-tools (^1.1.0)
    When prompted to install as a module, select development.config.php.dist
```

**Comment by weierophinney** [comment]
Cannot reproduce; I get prompted as detailed by @samsonasik when doing a fresh install.
