### ISSUE TITLE
Docker-compose on Windows

### ISSUE THREAD

**Issue by nynka** [zendframework/ZendSkeletonApplication#353]
When running the skeleton with docker-compose on Windows:
`$ docker-compose up -d`

I get an error when visiting the site:
> **Warning:** include(**{Local/Windows/Project/Path}**\module\Application\config/../view/layout/layout.phtml): failed to open stream: No such file or directory in **/var/www/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php** on line **502**
> 
> **Warning:** include(): Failed opening '**{Local/Windows/Project/Path}**\module\Application\config/../view/layout/layout.phtml' for inclusion (include_path='.:/usr/local/lib/php') in **/var/www/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php** on line **502**

Seems like there's a problem with resolving the correct view script paths in the container as it's pointing to the local Windows host paths.

Can I change something in the Dockerfile or docker-compose.yml to make it work?

**Comment by Ocramius** [comment]
> Seems like there's a problem with resolving the correct view script paths in the container as it's pointing to the local Windows host paths.

Any caching involved?

**Comment by nynka** [comment]
Yes, I turned off the config_cache_enabled setting in application.config.php and now It's working.

`'config_cache_enabled' => false,`

Thanks @Ocramius

**Comment by Ocramius** [comment]
@weierophinney maybe we should include the current application path or the host name in the cache file name? :|
