### ISSUE TITLE
Installed with mvc-i18n but no translate view helper.

### ISSUE THREAD

**Issue by tflin** [zendframework/ZendSkeletonApplication#358]
We are starting to migrate to zf3 on our projects. The ZendSkeletonApplication removed i18n translations, but our projects need localization. So we tried install zend-mvc-i18n using the zend-component-installer in ZendSkeletonApplication. It was installed successfully and the modules.config.php was with it.

But when we tried to use $this->translate('string') in the view templates as we did in zf2. The error: 
A plugin by the name "translate" was not found in the plugin manager Zend\View\HelperPluginManager
was shown. We tried many zf2 configurations but cannot find the correct way to fix it. Could someone check if there is any problem on using it with zf3 view helper? Thanks a lot.

**Comment by froschdesign** [comment]
Please no double postings! Thanks. (zendframework/zend-mvc-i18n/issues/3)
