### ISSUE TITLE
No prompts when running create-project...?

### ISSUE THREAD

**Issue by himynameisdave** [zendframework/ZendSkeletonApplication#362]
Hey just installed `composer` fresh on my machine and then used this command to init the project skeleton:
```
composer create-project -sdev zendframework/skeleton-application path/to/install
```
However unlike [the documentation](https://docs.zendframework.com/tutorials/getting-started/skeleton-application/), I was never prompted for things like the developer toolbar and database support. What did I do wrong?

**Comment by samsonasik** [comment]
it prompted on mine,:
```
    Do you want a minimal install (no optional packages)? Y/n
n

    Would you like to install the developer toolbar? y/N
y
    Will install zendframework/zend-developer-tools (^1.1.0)
    When prompted to install as a module, select development.config.php.dist
```

 you may need to clean up your composer cache.
```bash
$ rm -rf ~/.composer/cache
```

**Comment by samsonasik** [comment]
also, your case may you've choosed 'Y' instead of 'n' as documentation said:
```
If you answer "Y", or press enter with no selection, the installer will not raise
 any additional prompts, and finish installing your application.
 If you anser "n", it will continue prompting you:
```

**Comment by himynameisdave** [comment]
No the issue is that I don't get any prompts at all. Tried the cache clear, no luck 👎 

![screen shot 2016-07-19 at 9 42 55 am](https://cloud.githubusercontent.com/assets/4298089/16951967/3a783796-4d95-11e6-97f0-ff7b57439379.png)

**Comment by samsonasik** [comment]
that weird, you were installing old vesion. try to specify version in the command:
```bash
composer create-project zendframework/skeleton-application:^3.0 foo
```

**Comment by himynameisdave** [comment]
My argument is invalid apparently... mismatch PHP version? `php -v` indicates I have PHP version `5.5.30` installed on my system...
![screen shot 2016-07-19 at 10 16 52 am](https://cloud.githubusercontent.com/assets/4298089/16953403/dfe33b2c-4d9a-11e6-8d57-fa61c817c2b3.png)

**Comment by webimpress** [comment]
ZF3 requires PHP5.6+

**Comment by himynameisdave** [comment]
Just finished installing PHP7, runs fine now thanks everyone 👍
