### ISSUE TITLE
i have installed the zf3 and i am having his error Could not find a valid ServiceManager for LogProcessorManager

### ISSUE THREAD

**Issue by dinisptc** [zendframework/ZendSkeletonApplication#364]
Fatal error: Uncaught Zend\ModuleManager\Listener\Exception\RuntimeException: Could not find a valid ServiceManager for LogProcessorManager in C:\xampp\htdocs\etiju\vendor\zendframework\zend-modulemanager\src\Listener\ServiceListener.php on line 202

first i installed the skeleton app
then doctrineorm
then the entire framework with composer

i had all kind of errors

after installing the entire framework, with composer i am stuck with this error

**Comment by samsonasik** [comment]
try : 
```
composer require zendframework/zend-log
```
if you use this skeleton, you should prompted to include in config/modules.config.php, if you already have, you should just add manually in `config/modules.config.php` : 
```
return [
       'Zend\Log',
       'Application',
       // other modules.
];
```

**Comment by dinisptc** [comment]
thanks

i installed zend log before and its added to the modules config
i have two modules from a  zend 2 application
    'Autoriza',
    'AuthDoctrine',

maybe that's the problem i am going to keep trying i get the solution i will post it here 



return [
    'Zend\Cache',
    'Zend\Db',
    'Zend\Log',
    'Zend\Mail',
    'Zend\Mvc\Console',
    'Zend\Mvc\I18n',
    'Zend\I18n',
    'Zend\Mvc\Plugin\FilePrg',
    'Zend\Mvc\Plugin\FlashMessenger',
    'Zend\Mvc\Plugin\Identity',
    'Zend\Mvc\Plugin\Prg',
    'Zend\Navigation',
    'Zend\Serializer',
    'Zend\ServiceManager\Di',
    'Zend\Paginator',
    'Zend\Session',
    'Zend\Form',
    'Zend\InputFilter',
    'Zend\Filter',
    'Zend\Hydrator',
    'Zend\Router',
    'Zend\Validator',
    'Application',
    'Autoriza',
    'DoctrineModule',
    'DoctrineORMModule',
    'AuthDoctrine',
       
];

Using version ^2.9 for zendframework/zend-log
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

**Comment by dinisptc** [comment]
these two files on the config were with dist extension
removed that now its working, this one is fixed , thanks

development.config.php.dist

development.local.php.dist

**Comment by samsonasik** [comment]
please close this then
