### ISSUE TITLE
Need ZF2 Skeleton

### ISSUE THREAD

**Issue by mnino** [zendframework/ZendSkeletonApplication#367]
We have invested in ZF2 and need to continue using composer to build ZF2 (not ZF3) skeletons. How am I to do this now. This repository is now ZF3. Please advise. Thanks so much!

**Comment by webimpress** [comment]
You can use:

`composer create-project -sdev zendframework/skeleton-application:^2.3 path/to/install`

**Comment by mnino** [comment]
Thank you 😆

**Comment by samsonasik** [comment]
it can be closed then.

**Comment by mnino-glanbia** [comment]
Yes. Thank you. Please close issue.

**Comment by samsonasik** [comment]
if you're a @mnino  ===  @mnino-glanbia you can close it by @mnino account.

**Comment by mnino** [comment]
Thank you. Closed
