### ISSUE TITLE
Install for ZF2 - support with Doctrine

### ISSUE THREAD

**Issue by gulijiyag** [zendframework/ZendSkeletonApplication#370]
Everywhere I go in order to install Zend Skeleton, they use the same command with composer to install the skeleton, the thing is that Skeleton updated to zend-mvc 3.0.1 and I can't install Doctrine ORM Module for that reason. How to install skeleton for ZF2? I can't see a branch or anything for that.

**Comment by webimpress** [comment]
What command do you use to install ZF2?

You have to use ZendApplicationSkeleton in v2 for ZF2 apps:
`composer create-project -sdev zendframework/skeleton-application:^2.3 path/to/zf2-app`

`DoctineORMModule` is not yet compatible with ZF3: https://github.com/doctrine/DoctrineORMModule/pull/479

**Comment by gulijiyag** [comment]
@webimpress The command I said was: composer create-project -s dev zendframework/skeleton-application path/to/install

Everywhere, even on the documentation they don't specify the version and it's kinda confusing.

You specified 2.3, but the last version of ZF2 is 2.4. It means that the last skeleton made for ZF2 was to 2.3?

**Comment by samsonasik** [comment]
you can update composer.json yourself after install zf-skeleton-app ^2.3 as no longer tag after it for zf 2.* in zf-skeleton-app.

**Comment by gulijiyag** [comment]
@samsonasik Won't that give me problems with compatibility? I mean, the skeleton was made for ZF2.3 and the latest version for ZF2 is actually 2.4 ot even 2.5?

**Comment by samsonasik** [comment]
Please effort, just try, raise an issue if you found error

Warm regards,

Abdul Malik Ikhsan

Pada 22 Jul 2016, pukul 21.23, gulijiyag <notifications@github.com> menulis:

**Comment by gulijiyag** [comment]
It was just a question, maybe you have been through this and could spare me the same, but anyway, thank you.

**Comment by weierophinney** [comment]
I've just pushed a 2.5.0 release pinned to 57c1011, which was the last commit before we started work on the v3 skeleton. This will allow you to install a v2 skeleton using:

```bash
$ composer create-project "zendframework/skeleton-application:^2.5"
```

or, if you specify a directory:

```bash
$ composer create-project zendframework/skeleton-application my-project 2.5.0
```
