### ISSUE TITLE
zftool issue

### ISSUE THREAD

**Issue by gurubaksh** [zendframework/ZendSkeletonApplication#384]
All zf tool command returns html page. like zf.php version will return html page instead of version

**Comment by Ocramius** [comment]
Please report it against https://github.com/zendframework/zftool

**Comment by jasperf** [comment]
Same issues for me. Seems the tool [has not been updated to work with framework 3 as of yet](https://github.com/zendframework/ZFTool/issues/133). A shame though as I really love the tool for working with modules.
