### ISSUE TITLE
[2.5.1] Clean project installation won't show errors using provided Vagrantfile

### ISSUE THREAD

**Issue by chris-fa** [zendframework/ZendSkeletonApplication#387]
I ran the following commands

```
$ composer create-project --stability="dev" zendframework/skeleton-application blog-project ^2.4
$ cd blog-project
$ vagrant up
```

It fetched `2.5.1` (or that's what the `composer.lock` file says). Terminal echoed to visit `localhost:8085` which worked fine.

As I start the [blog tutorial](https://framework.zend.com/manual/2.4/en/in-depth-guide/first-module.html), I accidentally added a comma (`,`) after an interface name: 

`implements AutoloaderProviderInterface, { // note the comma there`

After saving and refreshing, Chrome gives me the following output:

```
The localhost page isn’t working

localhost is currently unable to handle this request.
HTTP ERROR 500
```

No stack trace, no errors, which leads me to think Apache isn't even processing the request. The project doesn't work out of the box. 

Any quick fixes or workarounds?

**Comment by adamlundrigan** [comment]
This installs a very old version of ZendSkeletonApplication (2.5.0).  Unless you have a specific reason to start with the 2.5.x series, I'd suggest using the latest stable version

**Comment by chris-fa** [comment]
Yes, I have specific reason to use 2.5 as our system is written in that version. However I solved the issue already. Apparently, regardless of PHP ini configuration, when printing phpinfo() **on a browser** it will say error display is set to off.  I enabled it using `ini_set()` but if you ask me that feels kind of smelly.
