### ISSUE TITLE
Dockerfile should also modify the document root in the default vhost

### ISSUE THREAD

**Issue by charlieman** [zendframework/ZendSkeletonApplication#389]
The Dockerfile changes apache's root directory to `/var/www/public` in apache2.conf but doesn't do it in the default virtual host configuration located in `/etc/apache2/sites-available/000-default.conf`. Changing the [sed line](https://github.com/zendframework/ZendSkeletonApplication/blob/a0049bb/Dockerfile#L7) to this should do it:

```
&& sed -i 's!/var/www/html!/var/www/public!g' /etc/apache2/apache2.conf \
  /etc/apache2/sites-available/000-default.conf \
```

**Comment by adamlundrigan** [comment]
#390 fixes this but stops updating `apache2.conf`.  Is it necessary to set the root in both files?

**Comment by charlieman** [comment]
I think in the default file is enough.

**Comment by Mezzle** [comment]
Yes, the `000-default.conf` is enough. `/var/www/html` is not mentioned in the main conf
