### ISSUE TITLE
config caching is enabled

### ISSUE THREAD

**Issue by nclundsten** [zendframework/ZendSkeletonApplication#392]
shouldn't be.

**Comment by Bittarman** [comment]
Did you use the development .dist config? 
https://github.com/zendframework/ZendSkeletonApplication/blob/master/config/development.config.php.dist#L15 should be turning it off.

**Comment by EvanDotPro** [comment]
I'd argue that's a little backwards for the skeleton, which is often used as a quick development starting point. IMO there should be a production .dist, and maybe a PRODUCTION.md file with more detailed information for deployment in the root or something.

**Comment by adamlundrigan** [comment]
Development mode is automatically enabled when skeleton is installed via `composer create-project`.  If installed by other method you'll need to [enable it manually](http://zendframework.github.io/tutorials/getting-started/skeleton-application/#development-mode).  I agree it would be a good addition to have a "going live" documentation blurb collecting advice for running the skeleton in production (composer optimizations, config caching, etc)

**Comment by weierophinney** [comment]
Just like in the ZF2 skeleton, we want production defaults enabled, and to use _local_ or _development_ configuration to override those locally in development. As @adamlundrigan notes, if you use `composer create-project`, development mode is enabled _by default_; the only reason it would not be is if you run that command with the `--no-scripts` and/or `--no-plugins` options. In such cases, you are stepping outside the documented installation method.

I'm happy to entertain a "going live" documentation blurb as @adamlundrigan suggests; if somebody would like to create that for the zend-mvc and/or tutorials documentation, I'll review it.
