### ISSUE TITLE
Zend Framework 2.4 LTS version

### ISSUE THREAD

**Issue by tdutrion** [zendframework/ZendSkeletonApplication#396]
Hi!

I was just wondering how come there is no version 2.4 as it is the LTS version of Zend Framework. Any interest in tagging one that long after the release and after tagging more recent versions?

**Comment by adamlundrigan** [comment]
Looks like Matthew added it:
https://github.com/zendframework/ZendSkeletonApplication/releases/tag/release-2.4.11

**Comment by tdutrion** [comment]
Thanks a lot!
