### ISSUE TITLE
unable to download Zend framework 2

### ISSUE THREAD

**Issue by phpnets** [zendframework/ZendSkeletonApplication#397]
Hi,
I need Zend Framework 2. I used to download ZF2 skeleton from github using composer and this command :  **php composer.phar create-project --stability="dev" zendframework/skeleton-application path/to/install**
. Recently I found it is downloading Zend Framework 3. I removed the --stability="dev" and checked but I didn't get ZendF2. Please let me know what is happened here and how to get ZendF2

**Comment by Ocramius** [comment]
You can run `composer create-project zendframework/skeleton-application:^2.2.6` and rely on the [2.2.6 version](https://github.com/zendframework/ZendSkeletonApplication/tree/zf/release-2.2.6)

**Comment by phpnets** [comment]
Hi,
I checked this **composer create-project zendframework/skeleton-application:^2.2.6** but got error "**Could not find package zendframework/skeleton-application with version 2.2.6**. I tried 2.4.9 also but failed. Please let me know what to do.

**Comment by Ocramius** [comment]
Try with `zendframework/skeleton-application:2.5.0` then: https://packagist.org/packages/zendframework/skeleton-application#2.5.0

**Comment by phpnets** [comment]
Thanks man. It works!!!. **I don't know why Zend peoples keep their documentation and helper guides so difficult to understand**.

**Comment by Ocramius** [comment]
@phpnets if you find the docs hard to understand, then contribute to them or report an issue on the https://github.com/zendframework/zf2-documentation repository (explaining what was complex for you). Also, it's not Zend, it's the community (which includes also me and you).

Also note that you should aim for ZF3 for new projects (since it's pretty much the same, but cleaned up)

**Comment by phpnets** [comment]
Ok done. I used to learn Zend1, Zend2 from https://framework.zend.com/manual/.... I thought there is a company Zend behind this.

**Comment by Ocramius** [comment]
They sponsor, but it's not built by the company :-)
