### ISSUE TITLE
Register with "Type: project" in Packagist

### ISSUE THREAD

**Issue by kaloyan-raev** [zendframework/ZendSkeletonApplication#404]
The _zendframework/skeleton-application_ package misses the "Type: project" attribute in Packagist:
https://packagist.org/packages/zendframework/skeleton-application

See the difference with the _zendframework/zend-expressive-skeleton_, which has this attribute:
https://packagist.org/packages/zendframework/zend-expressive-skeleton

As a result the Packagist API is query with filtering by project type then the Skeleton Application does not appear in the result list. Example query: https://packagist.org/search.json?q=skeleton-application&type=project

**Comment by Ocramius** [comment]
@kaloyan-raev can you send a PR for it?

**Comment by kaloyan-raev** [comment]
@Ocramius I am not sure what needs to be changed to fix the issue. I can see that the type is already set to "project" in composer.json: https://github.com/zendframework/ZendSkeletonApplication/blob/master/composer.json#L4

**Comment by mniewrzal** [comment]
Maybe something can be changed in packagist package configuration?

**Comment by weierophinney** [comment]
It's correctly showing up in Packagist at this time; I think it was likely awaiting a stable release with that metadata in place.
