### ISSUE TITLE
phpunit doesn't work on fresh installation

### ISSUE THREAD

**Issue by tasmaniski** [zendframework/ZendSkeletonApplication#405]
After I've install  ZF3 and run phpunit, I got a following error   

> PHP Fatal error:  Class 'Zend\Test\PHPUnit\Controller\AbstractHttpControllerTestCase' not found in /var/www/zf3-project/module/Application/test/Controller/IndexControllerTest.php on line 15

I can confirm that I have the class 
vendor/zendframework/zend-test/src/PHPUnit/Controller/AbstractHttpControllerTestCase.php 
and it's autoloaded in composer.json 

> "autoload-dev": {
>         "psr-4": {
>             "ApplicationTest\\": "module/Application/test/"
>         }
>     },
> "require-dev": {
>         "zendframework/zend-test": "^3.0.1"
> }

I installed project by default command from the doc 
`composer create-project -s dev zendframework/skeleton-application zf3-project`

**Comment by alextech** [comment]
Cannot reproduce. Did you run php unit that came with installer using:

```
$ ./vendor/bin/phpunit
```
?

**Comment by tasmaniski** [comment]
That was the problem, I run it with a "regular" phpunit command 

> $ phpunit --version
> PHPUnit 5.7.5 by Sebastian Bergmann and contributors.

With this one everything are passing. Thanks!

```
$ ./vendor/bin/phpunit
PHPUnit 5.7.5 by Sebastian Bergmann and contributors.
...                                                                 3 / 3 (100%)
Time: 92 ms, Memory: 9.75MB
OK (3 tests, 7 assertions)
```
