### ISSUE TITLE
don't undnerstand why we have those

### ISSUE THREAD

**Issue by svycka** [zendframework/ZendSkeletonApplication#408]
```
"zendframework/zend-component-installer": "^1.0 || ^0.3 || ^1.0.0-dev@dev",
"zendframework/zend-skeleton-installer": "^1.0 || ^0.1.3 || ^1.0.0-dev@dev",
```
also zendframework/zend-component-installer latest version is 0.7 so we don't allow 0.4, 0.5, 0.6... more comming?
versions 0.x can have BC breaks so when 1.0 will release then all the BC breaks will be in version 1.0 so how does it make sense to have ^0.3 instead of 0.* if we are good with BC breaks?
and as i understand @weierophinney did not want to allow to have 0.* so maybe we should remove ^1.0 and ^1.0.0-dev@dev

**Comment by weierophinney** [comment]
The installers use the Composer API, so, while _internally_ they may change, and for _extension_ they may change, for the purposes of the skeleton application, where we depend on them directly, their ability to interact with Composer to accomplish installation details _is stable_. As such, we can use any of the 0.X versions as well as the 1.0 versions.
