### ISSUE TITLE
Command "development-status" is not defined.

### ISSUE THREAD

**Issue by josiahking** [zendframework/ZendSkeletonApplication#415]
Hello after i installed the skeleton application using composer, while following the tutorial on https://docs.zendframework.com/tutorials/getting-started/skeleton-application/ i tried to enable development but got this error  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "development-status" is not defined.

**Comment by webimpress** [comment]
@josiahking are you sure you try to call this command _inside_ directory where you've installed the skeleton application?

I've just tried it:
```
$ composer create-project -s dev zendframework/skeleton-application path/to/install
# I've chosen minimal installation
$ cd path/to/install
$ composer development-enable
```

When you used `create-project` development mode will be enabled automatically.

**Comment by josiahking** [comment]
@webimpress Yes that's what i was doing, i noticed even the "composer development-status" returns the same error.
Should i do it outside the project directory?

**Comment by webimpress** [comment]
No, definitely inside the project directory.
Please write more information, how did you install the skeleton, what options have you chosen during the installation, and provide your `composer show` results.

**Comment by josiahking** [comment]
I have created in instead zendframework skeleton app following the tutorial on this https://docs.zendframework.com/tutorials/

Below is the composer show

c:\workspace\web\Apache24\www\project>composer show
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
doctrine/instantiator               1.0.4  A small, lightweight utility to instantiate objects in PHP without invo...
phpdocumentor/reflection-docblock   2.0.4
phpspec/prophecy                    v1.4.1 Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage           2.1.5  Library that provides collection, processing, and rendering functionali...
phpunit/php-file-iterator           1.4.0  FilterIterator implementation that filters files based on a list of suf...
phpunit/php-text-template           1.2.0  Simple template engine.
phpunit/php-timer                   1.0.5  Utility class for timing
phpunit/php-token-stream            1.4.1  Wrapper around PHP's tokenizer extension.
phpunit/phpunit                     4.7.2  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects        2.3.3  Mock Object library for PHPUnit
sebastian/comparator                1.1.1  Provides the functionality to compare PHP values for equality
sebastian/diff                      1.3.0  Diff implementation
sebastian/environment               1.2.2  Provides functionality to handle HHVM/PHP environments
sebastian/exporter                  1.2.0  Provides the functionality to export PHP variables for visualization
sebastian/global-state              1.0.0  Snapshotting of global state
sebastian/recursion-context         1.0.0  Provides functionality to recursively process PHP variables
sebastian/version                   1.0.5  Library that helps with managing the version number of Git-hosted PHP p...
symfony/yaml                        v2.7.0 Symfony Yaml Component
zendframework/zend-authentication   2.5.1  provides an API for authentication and includes concrete authentication...
zendframework/zend-barcode          2.5.1  provides a generic way to generate barcodes
zendframework/zend-cache            2.5.1  provides a generic way to cache any data
zendframework/zend-captcha          2.5.1
zendframework/zend-code             2.5.1  provides facilities to generate arbitrary code using an object oriented...
zendframework/zend-config           2.5.1  provides a nested object property based user interface for accessing th...
zendframework/zend-console          2.5.1
zendframework/zend-crypt            2.5.1
zendframework/zend-db               2.5.1
zendframework/zend-debug            2.5.1
zendframework/zend-di               2.5.1
zendframework/zend-dom              2.5.1  provides tools for working with DOM documents and structures
zendframework/zend-escaper          2.5.1
zendframework/zend-eventmanager     2.5.1
zendframework/zend-feed             2.5.1  provides functionality for consuming RSS and Atom feeds
zendframework/zend-file             2.5.1
zendframework/zend-filter           2.5.1  provides a set of commonly needed data filters
zendframework/zend-form             2.5.1
zendframework/zend-http             2.5.1  provides an easy interface for performing Hyper-Text Transfer Protocol ...
zendframework/zend-i18n             2.5.1
zendframework/zend-i18n-resources   2.5.1  Provides validator translations for zend-i18n's Translator
zendframework/zend-inputfilter      2.5.1
zendframework/zend-json             2.5.1  provides convenience methods for serializing native PHP to JSON and dec...
zendframework/zend-loader           2.5.1
zendframework/zend-log              2.5.1  component for general purpose logging
zendframework/zend-mail             2.5.1  provides generalized functionality to compose and send both text and MI...
zendframework/zend-math             2.5.1
zendframework/zend-memory           2.5.1
zendframework/zend-mime             2.5.1
zendframework/zend-modulemanager    2.5.1
zendframework/zend-mvc              2.5.1
zendframework/zend-navigation       2.5.1  provides support for managing trees of pointers to web pages
zendframework/zend-paginator        2.5.1
zendframework/zend-permissions-acl  2.5.1  provides a lightweight and flexible access control list (ACL) implement...
zendframework/zend-permissions-rbac 2.5.1  provides a role-based access control management
zendframework/zend-progressbar      2.5.1  component to create and update progressbars in different environments
zendframework/zend-serializer       2.5.1  provides an adapter based interface to simply generate storable represe...
zendframework/zend-server           2.5.1
zendframework/zend-servicemanager   2.5.1
zendframework/zend-session          2.5.1  manage and preserve session data, a logical complement of cookie data, ...
zendframework/zend-soap             2.5.1
zendframework/zend-stdlib           2.5.1
zendframework/zend-tag              2.5.1  a component suite which provides a facility to work with taggable Items
zendframework/zend-test             2.5.1
zendframework/zend-text             2.5.1
zendframework/zend-uri              2.5.1  a component that aids in manipulating and validating ┬╗ Uniform Resourc...
zendframework/zend-validator        2.5.1  provides a set of commonly needed validators
zendframework/zend-version          2.5.1
zendframework/zend-view             2.5.1  provides a system of helpers, output filters, and variable escaping
zendframework/zend-xmlrpc           2.5.1
zendframework/zendframework         2.5.1  Zend Framework 2
zendframework/zendxml               1.0.0  Utility library for XML usage, best practices, and security in PHP

**Comment by xtreamwayz** [comment]
I'm not sure what you did, but [zfcampus/zf-development-mode](https://github.com/zendframework/ZendSkeletonApplication/blob/master/composer.json#L19) is not installed.

Also to call `composer development-status`, it must be defined in your [composer.json script](https://github.com/zendframework/ZendSkeletonApplication/blob/master/composer.json#L115-L117).

Can you show your composer.json file?

**Comment by weierophinney** [comment]
Based on the composer output above, it looks like @josiahking has installed the 2.5 series of the skeleton, and not a 3.0.X version (which is what the tutorials on docs.zendframework.com target). 

How did you create your application, @josiahking ? The 2.5 series _does not_ have zf-development-mode enabled, nor are there commands for it in the `composer.json`. Is it possible you're on an old PHP version, say 5.5 or earlier? If so, that could be why you received the 2.5 version, as 3.0 requires PHP 5.6 and up.

**Comment by AlexanderRojas** [comment]
Hi ¡
1. composer update.
2. compuser install.
.... Then now you can do:
3. composer development-status 
4. composer development-enable
