### ISSUE TITLE
Is development.local.php really the right name?

### ISSUE THREAD

**Issue by bitwombat** [zendframework/ZendSkeletonApplication#417]
`development.local.php` gets picked up by the `*local.php` glob, but I think that's misleading.  It's not so much a local file as a development file, right?  

So should it (and its .dist files) be named `local-development.php`

There's probably a reason I'm missing...

It does cause a slight problem since, when development mode is disabled,  `development.local.php` still gets loaded.

**Comment by froschdesign** [comment]
Look at the [`.gitignore` file](https://github.com/zendframework/ZendSkeletonApplication/blob/master/config/autoload/.gitignore).

**Comment by bitwombat** [comment]
And?   Not getting your point.

The top level .gitignore ignores config/development.config.php  

My point is that I think the file is named wrong.

**Comment by froschdesign** [comment]
> The top level .gitignore ignores config/development.config.php

Follow the link in my comment: 

`config/autoload/.gitignore`

```
local.php
*.local.php
```

**Comment by bitwombat** [comment]
Yeah, I get that.  But the skeleton has it named development.local.php.dist.  Regardless of .gitignore, this is how the file is in the repository.

**Comment by xtreamwayz** [comment]
@bitwombat That's exactly how that file should be in the repository. It makes sure you can distribute your development settings with others. This is where zfcampus/zf-development-mode comes in. If you enable development mode with it, it copies `config/autoload/development.local.php.dist` to `config/autoload/development.local.php`. That way it gets picked up by that glob but it won't make it into your production as it's ignored by git, unless you run the enable command there as well (which you should never do).

**Comment by bitwombat** [comment]
@xtreamwayz Yep, I got that too.  The way its named in the repo affects (and should affect) what it ends up named in my project.

I've failed at explaining this to two of you, so let me cop that and try again :)  Thanks for your patience.

In `app/config/development.config.php`, there's:

        'config_glob_paths' => [realpath(__DIR__) . '/autoload/{,*.}{global,local}-development.php'],

That pattern is mean to pick up local development files called `*.local-development.php`.  But with the way the "local development" file is currently named in this repo, it doesn't get picked up by this glob - it gets picked up by the `*.local.php` glob from the main app config file.

This bit me because I bootstrap my ZF3 application for command-line runs with Behat.  A config key/value I added to `development.local.php` wasn't getting read, and that was why.

To be true with the intent of the glob in the code snippet above, I think this file was meant to be named `local-development.php` (of course `local-development.php.dist` in the repo).

Does that make any sense?

Looking at zfcampus' enable/disable, that would need to change too.  And when you look at how consistent the filenames there look:

    const DEVEL_CONFIG      = 'config/development.config.php';
    const DEVEL_CONFIG_DIST = 'config/development.config.php.dist';
    const DEVEL_LOCAL       = 'config/autoload/development.local.php';
    const DEVEL_LOCAL_DIST  = 'config/autoload/development.local.php.dist';

I'm starting to think maybe the glob should change, not the filename.

**Comment by xtreamwayz** [comment]
> It does cause a slight problem since, when development mode is disabled, development.local.php still gets loaded.

There might be something wrong or you found a bug. If you disable development mode, that file should be removed.

> This bit me because I bootstrap my ZF3 application for command-line runs with Behat. A config key/value I added to development.local.php wasn't getting read, and that was why.

So what exactly are you trying to do? Loading the development config only without the normal config files?

> To be true with the intent of the glob in the code snippet above, I think this file was meant to be named local-development.php (of course local-development.php.dist in the repo).
> Does that make any sense?

Not really. For example in zend-expressive there are no modules like in zend-mvc and `.local-development.php` is not loaded. The only way to load configuration is by adding the .local.php extension. Renaming `development.local.php` to `local-development.php` would break development-mode for zend-expressive.

For zend-mvc I don't know why `.local-development.php` was chosen. It might have well been called `.development.php`. I'm guessing the reason to actually have the `.local-development.php` extension is so you can have module specific development config like `zend-developer-tools.local-development.php`.
