### ISSUE TITLE
Zend Version

### ISSUE THREAD

**Issue by Marcelinne** [zendframework/ZendSkeletonApplication#419]
Hello everybody, I'm having problems with Zend version, when I check by terminal, it shows:
`echo "Zend engine version: " . zend_version();`
`Zend engine version: 2.6.0`

But in my composer file I have:
`"zendframework/zend-mvc": "^3.0.1",`

So I'm confused, I think I' having zend version conflicts, how I can solve this?

Thanks in advance.

**Comment by alextech** [comment]
Zend engine is not related to Zend Framework. One is PHP C library which executes php code, other is the application framework

**Comment by Marcelinne** [comment]
@alextech so if I'm using different versions there will not be problems when building appplications with zend framework? I'm newer, thanks for the patience and for the answer =)

**Comment by alextech** [comment]
It's not newer or older. It's literally different products, like Laravel vs php or ruby vs Linux. Name is pure marketing coincidence.

**Comment by alextech** [comment]
No, You will not have a problem :)

**Comment by Marcelinne** [comment]
jajjaja oks got it, thanks a lot for the clarification
