### ISSUE TITLE
How to prevent auto clearing cache?

### ISSUE THREAD

**Issue by boufenzi** [zendframework/ZendSkeletonApplication#421]
Hello , i'm facing a problem with zend cache , in production in our company the zend cache (in my backend)  automatically clear my cache once in awhile  and slow down all my mysql server for 2minutes because his doing a lot of insert at the same time and more than 2000 select query , i want if possible how can i disable auto cleaning zend cache and make it manually when i want to do it myself , can someone help please , i'm facing this problem for many month now 

Thos are some of the queries who execute themselve for a thousand time depends on how many users i have in my backoffice_users table  : 
SELECT `m`.* FROM `backoffice_users_groups` AS `i` INNER JOIN `groups` AS `m` ON `i`.`group_id` = `m`.`id` WHERE (`i`.`user_id` = 1)

Same thing for groups table : 
[0.26 ms] SELECT `flags`.* FROM `flags` WHERE (`id` = 28) LIMIT 1

those queries are executed in  Library/zend/manager.php on the _generateFromDb function

**Comment by Ocramius** [comment]
> how can i disable auto cleaning zend cache and make it manually when i want to do it myself

Unaware of such functionality - can you make an example of how the cache is configured?

**Comment by froschdesign** [comment]
@boufenzi 
> look at libray/zend/manager.php in the _generateFromDb function

Sorry, but this is userland code and not a part of the Zend Framework.

> I tried thoes options in core.php…

The same here.

**Comment by boufenzi** [comment]
if i'm not mistaken, it's part of Zend Skeleton Application, am i in the right issue forum ??

**Comment by froschdesign** [comment]
> it's part of Zend Skeleton Application

No, it's not. ZF doesn't use a directory name `library`.

> am i in the right issue forum ??

This is the issue / bug tracker for the skeleton application, but not a forum. Please use [discourse.zendframework.com](https://discourse.zendframework.com/) for further questions.

**Comment by boufenzi** [comment]
ok thank you for your help and for your quick responses

**Comment by froschdesign** [comment]
Use the forum and add some code, I think this could help.
