### ISSUE TITLE
I followed the tutorial and added a new album module besides application module, however 500 error 

### ISSUE THREAD

**Issue by jobsfan** [zendframework/ZendSkeletonApplication#424]
https://github.com/jobsfan/zf3document/tree/master/src/module/Album
I started via this tutorial page https://docs.zendframework.com/tutorials/getting-started/modules/, because my project is not an empty one, I have already had a application module which inherit from skeleton.
The steps as follow:
1. create the folder and sub-folder according to the official tutorial. 
2. create module/Album/src/Module.php and copy the codes into it.
3. modify composer.json and add "Album\\": "module/Album/src/"
4. I didn't not run **composer dump-autoload** because My local programming env is windows, I am not good at operating this beyond windows 10. So I just create /module/Album/config/module.config.php by hand and copy the tutorial code into it.
5. add ** 'Album' **  to the global configuration config/modules.config.php
Then, my website crashed, no zf kind error shows but 500 error, I just can find a error message from nginx error log like:

PHP Fatal error:  Uncaught Zend\ModuleManager\Exception\RuntimeException: Module (Album) could not be initialized

Is there anything I missed? Looking forward to you kind reply when you have time, thank you.
All my code is here https://github.com/jobsfan/zf3document/tree/master/src
Ps: My website that I am trying has a crontab to git pull the codes from my github account. It means my website code is the same as my github.

**Comment by alextech** [comment]
*composer dump-autoload* is one of the most important steps you cannot skip. It is not something that can be compensated by hand, as it triggers composer to writes into its own internal autoloader (outside of zend) instructions of how to find classes based on the composer.json configuration. This is true for any framework you pick.

Why is running composer on windows causing you a problem? How did you install it? If you just download PHAR version of it and execute *php composer.phar dump-autoload* might work. If you want more assistance, please post further replies on https://discourse.zendframework.com/

**Comment by jobsfan** [comment]
@alextech thanks for your reply! I will try to run the composer command.

**Comment by jobsfan** [comment]
@alextech , I just followed your advise and my problems solved! Thank you again!

**Comment by alextech** [comment]
@jobsfan you are welcome, glad it works! Can you close the issue please?

**Comment by jobsfan** [comment]
@alextech  I don't know how to close it, you can close it for me. I am not very familiar with the github, I am a newbie here. sorry for the inconvenience.

**Comment by Ocramius** [comment]
@jobsfan it's already closed :-)
