### ISSUE TITLE
a question about zf3 tutorial album perform in zend studio 13.6.1 IDE

### ISSUE THREAD

**Issue by jobsfan** [zendframework/ZendSkeletonApplication#425]
I followed the steps on the official tutorial. But the zend studio 13.6.1 raise two yellow exclamation mark like the following :
![error not found](https://wendangs.com/img/github/2018-01-01-1.jpg)

I thought it is the standard way because I strictly the same with the code and the steps according to the official tutorial. https://docs.zendframework.com/tutorials/getting-started/database-and-models/

My code is here https://github.com/jobsfan/zf3document/blob/master/src/module/Album/src/Module.php

You might think it is no big deal since my album work well https://wendangs.com/album, But it is a big deal to me, The error tips shows in the official IDE make me very nervous. Is there any mistakes in my code?

**Comment by Ocramius** [comment]
No mistakes there: ::class is a meta-constant that is evaluated at
parse-time by PHP, so no errors nor issues will arise at runtime.

The class-oriented naming (even when the class doesn't exist) is preferred
for Zend\ServiceManager configurations.

**Comment by jobsfan** [comment]
@Ocramius , thanks for your reply! However the zend studio raise yellow exclamation mark makes me uncomfortable. As you known, zendframework 3 is the official framework, zend studio 13.6.1 is the official IDE. and the tutorial is the official tutorial. The most standard way I followed in coding. I should not deserve a yellow exclamation mark  :(

**Comment by Ocramius** [comment]
You can simply use a string in that code location, if you are uncomfortable
with the notice. Any IDE will mark that, but note that Zend studio is not
the "official ide", as zendframework is a community project.

**Comment by alextech** [comment]
Its actually called *AlbumTable*, without *Gateway* based on what it is inside the Model directory.

**Comment by alextech** [comment]
I was in process of making PR about correcting ::class names, then noticed docs had an intentional tone to calling a `Model\AlbumTable` class as `Model\AlbumTableGateway` in SM. Is using non-existing classes as service names "a thing" I didn't notice these days?

**Comment by jobsfan** [comment]
@alextech Thanks for your reply! I am not very understand what you mean because I am in a non-english-speaking Country and my English is very pool.
I guess you may modify the usage of that in the tutorial, right?  I guess it is not possible to improve the zend studio notice, right?
I known there are a lot of geniuses programmer in the world who can fulfill big project with a notepad on plain text way. But for me, I am deep dependent to IDE, especially zendstudio.

**Comment by Sunduck** [comment]
You can fix IDE issues with this code by using actual factory class

create file Application/Model/Factory/AlbumTableFactory.php

`<?php

namespace Application\Model\Factory;

use Application\Model\Album;
use Application\Model\AlbumTable;
use Interop\Container\ContainerInterface;
use Zend\Db\Adapter\AdapterInterface;
use Zend\Db\ResultSet\ResultSet;
use Zend\Db\TableGateway\TableGateway;
use Zend\ServiceManager\Factory\FactoryInterface;

class AlbumTableFactory implements FactoryInterface
{
    public function __invoke(ContainerInterface $container, $requestedName, array $options = null)
    {
        $resultSetPrototype = new ResultSet();
        $resultSetPrototype->setArrayObjectPrototype(new Album());

        $tableGateway = new TableGateway('album', $container->get(AdapterInterface::class), null, $resultSetPrototype);
        return new AlbumTable($tableGateway);
    }
}`

And fix getServiceConfig() to look like this

`public function getServiceConfig()
    {
        return [
            'factories' => [
                Model\AlbumTable::class => Model\Factory\AlbumTableFactory::class
            ],
        ];
    }`

**Comment by alextech** [comment]
@jobsfan it is possible. Just use `Model\AlbumTable` whereever it says `Model\AlbumTableGateway`.
