### ISSUE TITLE
Another problem when I follow the tutorial, it says SQLSTATE[HY000]: General error: 14 unable to open database file

### ISSUE THREAD

**Issue by jobsfan** [zendframework/ZendSkeletonApplication#426]
I got a 500 error when I am trying to add a new record.

![](https://wendangs.com/img/github/2018-01-05-1.jpg)

My code hosted here https://github.com/jobsfan/zf3document/tree/master/src
Before it shows has no right to write, I chown the zftutorial.db file to www-data:www-data, then I got a different error as the above pic. I run the php -m in the command line, and it has sqlite3 listed.

By the way, will you ban my account since I am keep raising a lot of issues here under the office skeleton? 
I dont' know whether there is a place that I can ask question free.  a long time ago I tried to post my questions to the zf bbs. However no answer in a long time. in fact, never.

**Comment by Sunduck** [comment]
It's SQlite issue, probably incorrect permissions for your webserver user.

**Comment by alextech** [comment]
@jobsfan better place to ask for help is https://zendframework.slack.com and https://discourse.zendframework.com/ I do not know what zf bbs even is XD.

**Comment by jobsfan** [comment]
@alextech Thank you for these websites. I will try to ask questions there.

@Sunduck I will follow your advise. :100:

**Comment by jobsfan** [comment]
@Sunduck 
I cd to the folder of the location of zftutorial.db, and run **chmod +r zftutorial.db**, however, still raise the **SQLSTATE[HY000]: General error: 14 unable to open database file** message.

**Comment by Ocramius** [comment]
The issue with permissions is generally because the file is owned by a different user, not just because of the flags. In your case, you might want to `chown` the file. If you run the PHP process from your own user:

```sh
chown $(whoami) zftutorial.db
```

Closing here, as this is not an issue with the project itself - feel free to keep asking questions though.

**Comment by jobsfan** [comment]
@Ocramius I followed your advise, and run:
`chown -R www-data:www-data zftutorial.db`
However, nothing different.

===================================================
I run `php -m` and got:
![](https://wendangs.com/img/github/2018-01-12-01.jpg)

I view the php page with `phpinfo();` in it and got:
![](https://wendangs.com/img/github/2018-01-12-02.jpg)

![](https://wendangs.com/img/github/2018-01-12-03.jpg)

Any other idea?

**Comment by froschdesign** [comment]
@jobsfan 
The folder where the database file is included must also be writable.

---

For the future please the [forum](https://discourse.zendframework.com/) or [slack](http://zendframework.slack.com/) if you have question or problems. Thanks!
