### ISSUE TITLE
Zend\I18n does not get injected in modules.config.php

### ISSUE THREAD

**Issue by rkeet** [zendframework/ZendSkeletonApplication#432]
During the installation you can pick where/if to inject modules. Upon selecting "modules.config.php" ([1]) and to remember the answer for similar modules, it does not inject `Zend\I18n` into the modules.config.php module list. 

It _does_ inject `Zend\Mvc\I18n`, which obviously is not the same (but may the reason  `Zend\I18n` was overlooked?)

**Comment by Xerkus** [comment]
This was resolved in april 2018 with zend-i18n 2.8.0
