### ISSUE TITLE
support zend-stratigility 3?

### ISSUE THREAD

**Issue by samsonasik** [zendframework/ZendSkeletonApplication#433]
When I tried to use middleware in zend-mvc 3, it require to install `zend-stratigility` as it seems it no longer required, so I add the `zend-stratigility` to require with command:

```
composer require zendframework/zend-stratigility
```

and it installed the `zend-stratigility` 3. After it installed, I got the following error: 

```
( ! ) Fatal error: Uncaught Error: Call to undefined method Zend\Stratigility\MiddlewarePipe::setResponsePrototype() in /Users/samsonasik/www/zf-mvc3/vendor/zendframework/zend-mvc/src/MiddlewareListener.php on line 134
( ! ) Error: Call to undefined method Zend\Stratigility\MiddlewarePipe::setResponsePrototype() in /Users/samsonasik/www/zf-mvc3/vendor/zendframework/zend-mvc/src/MiddlewareListener.php on line 134
```
So, I downgraded the version to v2 with command: 

```
composer require zendframework/zend-stratigility:^2.0
```

And it works. 

How about support zend-stratigility v3 as well?

**Comment by froschdesign** [comment]
Duplicate of https://github.com/zendframework/zend-mvc/issues/283
