### ISSUE TITLE
Faulty link on homepage

### ISSUE THREAD

**Issue by stefkes** [zendframework/ZendSkeletonApplication#440]
The "Explore ZF modules" link on the homepage of the skeleton app goes to modules.zendframework.com which redirects to zfmodules.com which seems to be some Danish car rental agency or template site.

(It's really disappointing to see the ZF3 docs are as messy and incoherent as the ZF2 docs, and this just takes the unprofessionalism to another level. Whoever's in charge could really learn something from certain other PHP frameworks that have excellent docs and are a joy to work with, which ZF is the complete opposite of)

**Comment by weierophinney** [comment]
zfmodules is a community-run site. I'll reach out to those who run it to find out what's going on. If the site is no longer maintained, we'll remove the link from the skeleton.

Regarding this:

> Whoever's in charge could really learn something from certain other PHP frameworks that have excellent docs and are a joy to work with, which ZF is the complete opposite of)

Considering that the project is primarily community-driven, and thus relies on volunteer efforts (even for matters like the website), this is a rather abrasive way to draw attention to your issue. In the future, please be more considerate towards those _who are providing you something for free_. As an example, you could have dropped the entire second paragraph and said something along the lines of "As this provides an initial impression of the project, the link should likely be removed or fixed." It would provide the same sense of urgency without being an ad-hominem attack on the maintainers.

**Comment by weierophinney** [comment]
I've corrected it in the meantime by modifying the modules.zendframework.com domain to redirect to a Packagist search for ZF modules.
