### ISSUE TITLE
Zend\Form\Form::bindValues(array $values = Array) must be compatible with Zend\Form\Fieldset::bindValues(array $values = Array, ?array $validationGroup = NULL)

### ISSUE THREAD

**Issue by gzhh** [zendframework/ZendSkeletonApplication#441]
In my enviroment
php7.2, composer serve

I new Zend\Form\Form in controller, got this error.

Fatal error: Declaration of Zend\Form\Form::bindValues(array $values = Array) must be compatible with Zend\Form\Fieldset::bindValues(array $values = Array, ?array $validationGroup = NULL) in /path_to_www/zend_skeleton/vendor/zendframework/zend-form/src/Form.php on line 24

So i change
public function bindValues(array $values = [])
to
public function bindValues(array $values = [], array $validationGroup = null)
in /vendor/zendframework/zend-form/src/Form.php

Finally the error disappeare.

**Comment by Ocramius** [comment]
What version of zend-form?

**Comment by gzhh** [comment]
@Ocramius  zendframework/zend-form 2.10.2

**Comment by Ocramius** [comment]
Can you try updating to latest (2.14.x at the time of this writing) and see if the problem is still there?

**Comment by gzhh** [comment]
Yes, i update to 2.14.1 version and it fix it. Thx.
