### ISSUE TITLE
ZF issue tracker broken link

### ISSUE THREAD

**Issue by happydude** [zendframework/ZendSkeletonApplication#442]
The "ZF issue tracker" link in ZendSkeletonApplication/blob/master/module/Application/view/application/index/index.phtml links to a 404 on github.

**Comment by Xerkus** [comment]
Link is not broken actually, but it requires github user to be logged in

**Comment by BetaGravity** [comment]
You’re right, it works if I’m already signed in.

**Comment by happydude** [comment]
You’re right , it works if I’m already signed in. Thanks for the info.
