### ISSUE TITLE
Application module, IndexControllerTest is not working

### ISSUE THREAD

**Issue by KOVCHENKO** [zendframework/ZendSkeletonApplication#443]
Test causes:
Fatal error: Declaration of ApplicationTest\Controller\IndexControllerTest::setUp() must be compatible with Zend\Test\PHPUnit\Controller\AbstractControllerTestCase::setUp(): void in C:\My\Work\OSPanel\domains\zendtest\module\Application\test\Controller\IndexControllerTest.php on line 14 
due to lack of return type

**Comment by weierophinney** [comment]
As noted in #444, the tests provided with the skeleton have to work against all PHP versions we support, which includes PHP 5.6 and PHP 7.0. As such, we cannot have it support PHPUnit 8 at this time.
