### ISSUE TITLE
composer scripts is not compatible with windows 

### ISSUE THREAD

**Issue by AndyP1965** [zendframework/ZendSkeletonApplication#450]
composer.json:
in "scripts": { "post-create-project-cmd": [...] }

please change double quoting to single quoting in the line:

"php -r \"$file = file_get_contents('.gitignore'); $file = str_replace('composer.lock', '', $file); file_put_contents('.gitignore', $file);\""

**Comment by weierophinney** [comment]
Why? Can you explain the issue you encountered? What operating system were you using?

**Comment by weierophinney** [comment]
nm, I see you're on Windows. Still would like to know what error you encountered - the quoting should work cross-platform generally.

**Comment by AndyP1965** [comment]
Hello,

 

if you try to send in cmd.exe a commadline insidfe single quotes you will get an error.

 

 

php -r 'echo "abc";'

 

PHP Parse error:  syntax error, unexpected ''echo' (T_ENCAPSED_AND_WHITESPACE), expecting end of file in Command line code on line 1

 

Parse error: syntax error, unexpected ''echo' (T_ENCAPSED_AND_WHITESPACE), expecting end of file in Command line code on line 1

 

 

Without error::::

 

php -r "echo 'abc';"

abc

 

or:

 

php -r "echo \"abc\";"

abc

 

regards

Andreas

 

 

Von: weierophinney 
Gesendet: Donnerstag, 21. November 2019 15:48
An: zendframework/ZendSkeletonApplication <ZendSkeletonApplication@noreply.github.com>
Cc: AndyP1965 <andreas.paulick@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [zendframework/ZendSkeletonApplication] composer scripts is not compatible with windows (#450)

 

Why? Can you explain the issue you encountered? What operating system were you using?

**Comment by AndyP1965** [comment]
Hello weierophinney

 

It works fine für Windows OS but i guess for Linux wont works now because command line is not compatible for bash replacment. ☹

 

"shell" : "php -r '$file = file_get_contents(\".gitignore\"); $file = str_replace(\"composer.lock\", \"\", $file); file_put_contents(\".gitignore\", $file);'",

"cmd" :   "php -r \"$file = file_get_contents('.gitignore'); $file = str_replace('composer.lock', '', $file); file_put_contents('.gitignore', $file);\""

 

or  use an external php file with php -f ...... ( compatible to both )

 

regards

Andreas

 

 

 

 

Von: weierophinney 
Gesendet: Donnerstag, 21. November 2019 22:06
An: zendframework/ZendSkeletonApplication <ZendSkeletonApplication@noreply.github.com>
Cc: AndyP1965 <andreas.paulick@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [zendframework/ZendSkeletonApplication] composer scripts is not compatible with windows (#450)

 

Closed #450 <https://github.com/zendframework/ZendSkeletonApplication/issues/450>  via #451 <https://github.com/zendframework/ZendSkeletonApplication/pull/451> .

**Comment by weierophinney** [comment]
@AndyP1965 Just confirmed on Linux. Will try to get another option in place shortly.
