### ISSUE TITLE
Could an .editorconfig file be added to this?

### ISSUE THREAD

**Issue by lyda** [zendframework/ZendSkeletonApplication#453]
I note that [zfbot](https://github.com/zendframework/zfbot) has one so was wondering if this skeleton could use that one or something like it?

**Comment by weierophinney** [comment]
zfbot only has one because it was started from a hubot release. We generally tend not to provide editor/IDE-related configuration files, as there's so many different ones.

**Comment by lyda** [comment]
Uh, OK.  I would note that .editorconfig exists to solve that exact problem. But, hey, you do you.

https://editorconfig.org/
